FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        curl \
    && rm -rf /var/lib/apt/lists/*

COPY search-service/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY search-service/ .

EXPOSE 8003

CMD ["python", "main.py"]
