"""
Prompt template registry.
"""

from graphrag_agent.config.prompts.search_prompts import (
    LOCAL_SEARCH_CONTEXT_PROMPT,
    LOCAL_SEARCH_KEYWORD_PROMPT,
    GLOBAL_SEARCH_MAP_PROMPT,
    GLOBAL_SEARCH_REDUCE_PROMPT,
    GLOBAL_SEARCH_KEYWORD_PROMPT,
    HYBRID_TOOL_QUERY_PROMPT,
    NAIVE_SEARCH_QUERY_PROMPT,
)
from graphrag_agent.config.prompts.agent_prompts import (
    GRAPH_AGENT_KEYWORD_PROMPT,
    GRAPH_AGENT_GENERATE_PROMPT,
    GRAPH_AGENT_REDUCE_PROMPT,
    DEEP_RESEARCH_THINKING_SUMMARY_PROMPT,
    EXPLORATION_SUMMARY_PROMPT,
    CONTRADICTION_IMPACT_PROMPT,
    HYBRID_AGENT_GENERATE_PROMPT,
    NAIVE_RAG_HUMAN_PROMPT,
)
from graphrag_agent.config.prompts.qa_prompts import (
    NAIVE_PROMPT,
    LC_SYSTEM_PROMPT,
    MAP_SYSTEM_PROMPT,
    REDUCE_SYSTEM_PROMPT,
    contextualize_q_system_prompt,
)

__all__ = [
    # Search tool prompts
    "LOCAL_SEARCH_CONTEXT_PROMPT",
    "LOCAL_SEARCH_KEYWORD_PROMPT",
    "GLOBAL_SEARCH_MAP_PROMPT",
    "GLOBAL_SEARCH_REDUCE_PROMPT",
    "GLOBAL_SEARCH_KEYWORD_PROMPT",
    "HYBRID_TOOL_QUERY_PROMPT",
    "NAIVE_SEARCH_QUERY_PROMPT",
    # Agent prompts
    "GRAPH_AGENT_KEYWORD_PROMPT",
    "GRAPH_AGENT_GENERATE_PROMPT",
    "GRAPH_AGENT_REDUCE_PROMPT",
    "DEEP_RESEARCH_THINKING_SUMMARY_PROMPT",
    "EXPLORATION_SUMMARY_PROMPT",
    "CONTRADICTION_IMPACT_PROMPT",
    "HYBRID_AGENT_GENERATE_PROMPT",
    "NAIVE_RAG_HUMAN_PROMPT",
    # QA prompts
    "NAIVE_PROMPT",
    "LC_SYSTEM_PROMPT",
    "MAP_SYSTEM_PROMPT",
    "REDUCE_SYSTEM_PROMPT",
    "contextualize_q_system_prompt",
]
